[project]
name = "lectures"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=7.3.0",
    "ipympl>=0.10.0",
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "pandas>=3.0.5",
    "pip>=26.2.1",
    "scikit-learn>=1.9.1",
    "seaborn>=0.13.2",
    "torch>=2.14.0",
    "wordcloud>=1.9.6",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.8",
]
